apiVersion: v2
name: trace
description: Qbrix Trace Service - EE event persistence to ClickHouse
type: application
version: 0.2.1  # x-release-please-version
appVersion: "0.2.1"  # x-release-please-version

keywords:
  - qbrix
  - trace
  - analytics
  - clickhouse
  - grpc
