# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0cqbrix.common\"\xaf\x01\n\x07\x43ontext\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06vector\x18\x02 \x03(\x02R\x06vector\x12?\n\x08metadata\x18\x03 \x03(\x0b\x32#.qbrix.common.Context.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"?\n\x03\x41rm\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n\x05index\x18\x03 \x01(\x05R\x05index\"Q\n\x04Pool\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12%\n\x04\x61rms\x18\x03 \x03(\x0b\x32\x11.qbrix.common.ArmR\x04\x61rms\"\x99\x02\n\nExperiment\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n\x07pool_id\x18\x03 \x01(\tR\x06poolId\x12\x1a\n\x08protocol\x18\x04 \x01(\tR\x08protocol\x12U\n\x0fprotocol_params\x18\x05 \x03(\x0b\x32,.qbrix.common.Experiment.ProtocolParamsEntryR\x0eprotocolParams\x12\x18\n\x07\x65nabled\x18\x06 \x01(\x08R\x07\x65nabled\x1a\x41\n\x13ProtocolParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x14\n\x12HealthCheckRequest\"\x9a\x01\n\x13HealthCheckResponse\x12G\n\x06status\x18\x01 \x01(\x0e\x32/.qbrix.common.HealthCheckResponse.ServingStatusR\x06status\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x42p\n\x10\x63om.qbrix.commonB\x0b\x43ommonProtoP\x01\xa2\x02\x03QCX\xaa\x02\x0cQbrix.Common\xca\x02\x0cQbrix\\Common\xe2\x02\x18Qbrix\\Common\\GPBMetadata\xea\x02\rQbrix::Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.qbrix.commonB\013CommonProtoP\001\242\002\003QCX\252\002\014Qbrix.Common\312\002\014Qbrix\\Common\342\002\030Qbrix\\Common\\GPBMetadata\352\002\rQbrix::Common'
  _globals['_CONTEXT_METADATAENTRY']._loaded_options = None
  _globals['_CONTEXT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EXPERIMENT_PROTOCOLPARAMSENTRY']._loaded_options = None
  _globals['_EXPERIMENT_PROTOCOLPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_CONTEXT']._serialized_start=31
  _globals['_CONTEXT']._serialized_end=206
  _globals['_CONTEXT_METADATAENTRY']._serialized_start=147
  _globals['_CONTEXT_METADATAENTRY']._serialized_end=206
  _globals['_ARM']._serialized_start=208
  _globals['_ARM']._serialized_end=271
  _globals['_POOL']._serialized_start=273
  _globals['_POOL']._serialized_end=354
  _globals['_EXPERIMENT']._serialized_start=357
  _globals['_EXPERIMENT']._serialized_end=638
  _globals['_EXPERIMENT_PROTOCOLPARAMSENTRY']._serialized_start=573
  _globals['_EXPERIMENT_PROTOCOLPARAMSENTRY']._serialized_end=638
  _globals['_HEALTHCHECKREQUEST']._serialized_start=640
  _globals['_HEALTHCHECKREQUEST']._serialized_end=660
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=663
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=817
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=759
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=817
# @@protoc_insertion_point(module_scope)
