"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import common_pb2 as _common_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FeedbackEvent(_message.Message):
    """Feedback event (used in Redis Streams, not gRPC directly)"""

    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    ARM_INDEX_FIELD_NUMBER: _builtins.int
    REWARD_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    request_id: _builtins.str
    """Correlates with SelectResponse.request_id"""
    arm_index: _builtins.int
    reward: _builtins.float
    timestamp_ms: _builtins.int
    @_builtins.property
    def context(self) -> _common_pb2.Context: ...
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        request_id: _builtins.str = ...,
        arm_index: _builtins.int = ...,
        reward: _builtins.float = ...,
        context: _common_pb2.Context | None = ...,
        timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arm_index", b"arm_index", "context", b"context", "experiment_id", b"experiment_id", "request_id", b"request_id", "reward", b"reward", "timestamp_ms", b"timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeedbackEvent: _TypeAlias = FeedbackEvent  # noqa: Y015

@_typing.final
class FlushBatchRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    """Optional: flush specific experiment, empty = all"""
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FlushBatchRequest: _TypeAlias = FlushBatchRequest  # noqa: Y015

@_typing.final
class FlushBatchResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENTS_PROCESSED_FIELD_NUMBER: _builtins.int
    events_processed: _builtins.int
    def __init__(
        self,
        *,
        events_processed: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["events_processed", b"events_processed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FlushBatchResponse: _TypeAlias = FlushBatchResponse  # noqa: Y015

@_typing.final
class GetStatsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    """Optional: specific experiment, empty = all"""
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetStatsRequest: _TypeAlias = GetStatsRequest  # noqa: Y015

@_typing.final
class ExperimentStats(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    TOTAL_EVENTS_FIELD_NUMBER: _builtins.int
    PENDING_EVENTS_FIELD_NUMBER: _builtins.int
    LAST_TRAIN_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    total_events: _builtins.int
    pending_events: _builtins.int
    last_train_timestamp_ms: _builtins.int
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        total_events: _builtins.int = ...,
        pending_events: _builtins.int = ...,
        last_train_timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id", "last_train_timestamp_ms", b"last_train_timestamp_ms", "pending_events", b"pending_events", "total_events", b"total_events"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExperimentStats: _TypeAlias = ExperimentStats  # noqa: Y015

@_typing.final
class GetStatsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExperimentStats]: ...
    def __init__(
        self,
        *,
        stats: _abc.Iterable[Global___ExperimentStats] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetStatsResponse: _TypeAlias = GetStatsResponse  # noqa: Y015
