"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import common_pb2 as _common_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreatePoolRequest(_message.Message):
    """Pool management"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ARMS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def arms(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Arm]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        arms: _abc.Iterable[_common_pb2.Arm] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arms", b"arms", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreatePoolRequest: _TypeAlias = CreatePoolRequest  # noqa: Y015

@_typing.final
class CreatePoolResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreatePoolResponse: _TypeAlias = CreatePoolResponse  # noqa: Y015

@_typing.final
class GetPoolRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_ID_FIELD_NUMBER: _builtins.int
    pool_id: _builtins.str
    def __init__(
        self,
        *,
        pool_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool_id", b"pool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPoolRequest: _TypeAlias = GetPoolRequest  # noqa: Y015

@_typing.final
class GetPoolResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPoolResponse: _TypeAlias = GetPoolResponse  # noqa: Y015

@_typing.final
class DeletePoolRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_ID_FIELD_NUMBER: _builtins.int
    pool_id: _builtins.str
    def __init__(
        self,
        *,
        pool_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool_id", b"pool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeletePoolRequest: _TypeAlias = DeletePoolRequest  # noqa: Y015

@_typing.final
class DeletePoolResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELETED_FIELD_NUMBER: _builtins.int
    deleted: _builtins.bool
    def __init__(
        self,
        *,
        deleted: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deleted", b"deleted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeletePoolResponse: _TypeAlias = DeletePoolResponse  # noqa: Y015

@_typing.final
class CreateExperimentRequest(_message.Message):
    """Experiment management"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ProtocolParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    POOL_ID_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    PROTOCOL_PARAMS_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    pool_id: _builtins.str
    protocol: _builtins.str
    enabled: _builtins.bool
    @_builtins.property
    def protocol_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig:
        """Feature gate config"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        pool_id: _builtins.str = ...,
        protocol: _builtins.str = ...,
        protocol_params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        enabled: _builtins.bool = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["feature_gate", b"feature_gate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "feature_gate", b"feature_gate", "name", b"name", "pool_id", b"pool_id", "protocol", b"protocol", "protocol_params", b"protocol_params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateExperimentRequest: _TypeAlias = CreateExperimentRequest  # noqa: Y015

@_typing.final
class FeatureGateConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROLLOUT_PERCENTAGE_FIELD_NUMBER: _builtins.int
    SCHEDULE_FIELD_NUMBER: _builtins.int
    DEFAULT_ARM_ID_FIELD_NUMBER: _builtins.int
    RULES_FIELD_NUMBER: _builtins.int
    rollout_percentage: _builtins.float
    """0.0 - 1.0"""
    default_arm_id: _builtins.str
    """Arm to return when gated"""
    @_builtins.property
    def schedule(self) -> Global___ScheduleConfig: ...
    @_builtins.property
    def rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___RuleConfig]: ...
    def __init__(
        self,
        *,
        rollout_percentage: _builtins.float = ...,
        schedule: Global___ScheduleConfig | None = ...,
        default_arm_id: _builtins.str = ...,
        rules: _abc.Iterable[Global___RuleConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schedule", b"schedule"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["default_arm_id", b"default_arm_id", "rollout_percentage", b"rollout_percentage", "rules", b"rules", "schedule", b"schedule"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeatureGateConfig: _TypeAlias = FeatureGateConfig  # noqa: Y015

@_typing.final
class ScheduleConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    END_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    start_timestamp_ms: _builtins.int
    end_timestamp_ms: _builtins.int
    def __init__(
        self,
        *,
        start_timestamp_ms: _builtins.int = ...,
        end_timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_timestamp_ms", b"end_timestamp_ms", "start_timestamp_ms", b"start_timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScheduleConfig: _TypeAlias = ScheduleConfig  # noqa: Y015

@_typing.final
class RuleConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    ARM_ID_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    condition: _builtins.str
    """Expression to evaluate against metadata"""
    arm_id: _builtins.str
    """Arm to return if rule matches"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        condition: _builtins.str = ...,
        arm_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arm_id", b"arm_id", "condition", b"condition", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RuleConfig: _TypeAlias = RuleConfig  # noqa: Y015

@_typing.final
class CreateExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiment(self) -> _common_pb2.Experiment: ...
    def __init__(
        self,
        *,
        experiment: _common_pb2.Experiment | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateExperimentResponse: _TypeAlias = CreateExperimentResponse  # noqa: Y015

@_typing.final
class GetExperimentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetExperimentRequest: _TypeAlias = GetExperimentRequest  # noqa: Y015

@_typing.final
class GetExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiment(self) -> _common_pb2.Experiment: ...
    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig: ...
    def __init__(
        self,
        *,
        experiment: _common_pb2.Experiment | None = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetExperimentResponse: _TypeAlias = GetExperimentResponse  # noqa: Y015

@_typing.final
class UpdateExperimentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ProtocolParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    PROTOCOL_PARAMS_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    enabled: _builtins.bool
    @_builtins.property
    def protocol_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig: ...
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        enabled: _builtins.bool | None = ...,
        protocol_params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "_feature_gate", b"_feature_gate", "enabled", b"enabled", "feature_gate", b"feature_gate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "_feature_gate", b"_feature_gate", "enabled", b"enabled", "experiment_id", b"experiment_id", "feature_gate", b"feature_gate", "protocol_params", b"protocol_params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__enabled: _TypeAlias = _typing.Literal["enabled"]  # noqa: Y015
    _WhichOneofArgType__enabled: _TypeAlias = _typing.Literal["_enabled", b"_enabled"]  # noqa: Y015
    _WhichOneofReturnType__feature_gate: _TypeAlias = _typing.Literal["feature_gate"]  # noqa: Y015
    _WhichOneofArgType__feature_gate: _TypeAlias = _typing.Literal["_feature_gate", b"_feature_gate"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enabled) -> _WhichOneofReturnType__enabled | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__feature_gate) -> _WhichOneofReturnType__feature_gate | None: ...

Global___UpdateExperimentRequest: _TypeAlias = UpdateExperimentRequest  # noqa: Y015

@_typing.final
class UpdateExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiment(self) -> _common_pb2.Experiment: ...
    def __init__(
        self,
        *,
        experiment: _common_pb2.Experiment | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateExperimentResponse: _TypeAlias = UpdateExperimentResponse  # noqa: Y015

@_typing.final
class DeleteExperimentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteExperimentRequest: _TypeAlias = DeleteExperimentRequest  # noqa: Y015

@_typing.final
class DeleteExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELETED_FIELD_NUMBER: _builtins.int
    deleted: _builtins.bool
    def __init__(
        self,
        *,
        deleted: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deleted", b"deleted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteExperimentResponse: _TypeAlias = DeleteExperimentResponse  # noqa: Y015

@_typing.final
class SelectRequest(_message.Message):
    """Selection (external API)"""

    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    @_builtins.property
    def context(self) -> _common_pb2.Context: ...
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        context: _common_pb2.Context | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SelectRequest: _TypeAlias = SelectRequest  # noqa: Y015

@_typing.final
class SelectResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ARM_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    IS_DEFAULT_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    is_default: _builtins.bool
    """True if returned by feature gate, not bandit"""
    @_builtins.property
    def arm(self) -> _common_pb2.Arm: ...
    def __init__(
        self,
        *,
        arm: _common_pb2.Arm | None = ...,
        request_id: _builtins.str = ...,
        is_default: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["arm", b"arm"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arm", b"arm", "is_default", b"is_default", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SelectResponse: _TypeAlias = SelectResponse  # noqa: Y015

@_typing.final
class FeedbackRequest(_message.Message):
    """Feedback"""

    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    REWARD_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    """signed token from SelectResponse containing all selection context"""
    reward: _builtins.float
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        reward: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request_id", b"request_id", "reward", b"reward"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeedbackRequest: _TypeAlias = FeedbackRequest  # noqa: Y015

@_typing.final
class FeedbackResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: _builtins.int
    accepted: _builtins.bool
    def __init__(
        self,
        *,
        accepted: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepted", b"accepted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeedbackResponse: _TypeAlias = FeedbackResponse  # noqa: Y015
