{{- if not .Values.config.jwt.existingSecret }}
{{- $name := include "proxy.jwtSecretName" . }}
{{- $key := .Values.config.jwt.existingSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $key }}: {{ .Values.config.jwt.secretKey | default (include "qbrix.persistentSecretValue" (dict "ctx" . "name" $name "key" $key)) | b64enc | quote }}
{{- end }}
{{- if not .Values.config.token.existingSecret }}
{{- $name := include "proxy.tokenSecretName" . }}
{{- $key := .Values.config.token.existingSecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $key }}: {{ .Values.config.token.secretKey | default (include "qbrix.persistentSecretValue" (dict "ctx" . "name" $name "key" $key)) | b64enc | quote }}
{{- end }}
