apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
data:
  # next.js application settings
  PORT: {{ .Values.config.port | quote }}
  HOSTNAME: {{ .Values.config.hostname | quote }}
  NODE_ENV: "production"
  {{- if and .Values.global.ee.enabled .Values.config.stripe.priceIdStarter }}
  STRIPE_PRICE_ID_STARTER: {{ .Values.config.stripe.priceIdStarter | quote }}
  {{- end }}
  {{- if and .Values.global.ee.enabled .Values.config.stripe.priceIdGrowth }}
  STRIPE_PRICE_ID_GROWTH: {{ .Values.config.stripe.priceIdGrowth | quote }}
  {{- end }}
  {{- if and .Values.global.ee.enabled .Values.config.stripe.priceIdScale }}
  STRIPE_PRICE_ID_SCALE: {{ .Values.config.stripe.priceIdScale | quote }}
  {{- end }}
  {{- if and .Values.global.ee.enabled .Values.config.stripe.priceIdPro }}
  STRIPE_PRICE_ID_PRO: {{ .Values.config.stripe.priceIdPro | quote }}
  {{- end }}
  {{- if and .Values.global.ee.enabled .Values.config.stripe.priceIdEnterprise }}
  STRIPE_PRICE_ID_ENTERPRISE: {{ .Values.config.stripe.priceIdEnterprise | quote }}
  {{- end }}
