apiVersion: v2
name: console
description: Qbrix Console - EE web application for managing experiments and pools
type: application
version: 0.2.1  # x-release-please-version
appVersion: "0.2.1"  # x-release-please-version

keywords:
  - qbrix
  - console
  - web
  - frontend
