"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _PlanTier:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PlanTierEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PlanTier.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PLAN_TIER_UNSPECIFIED: _PlanTier.ValueType  # 0
    PLAN_TIER_FREE: _PlanTier.ValueType  # 1
    PLAN_TIER_PRO: _PlanTier.ValueType  # 2
    PLAN_TIER_ENTERPRISE: _PlanTier.ValueType  # 3

class PlanTier(_PlanTier, metaclass=_PlanTierEnumTypeWrapper):
    """enums"""

PLAN_TIER_UNSPECIFIED: PlanTier.ValueType  # 0
PLAN_TIER_FREE: PlanTier.ValueType  # 1
PLAN_TIER_PRO: PlanTier.ValueType  # 2
PLAN_TIER_ENTERPRISE: PlanTier.ValueType  # 3
Global___PlanTier: _TypeAlias = PlanTier  # noqa: Y015

class _Role:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Role.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ROLE_UNSPECIFIED: _Role.ValueType  # 0
    ROLE_ADMIN: _Role.ValueType  # 1
    ROLE_MEMBER: _Role.ValueType  # 2
    ROLE_VIEWER: _Role.ValueType  # 3

class Role(_Role, metaclass=_RoleEnumTypeWrapper): ...

ROLE_UNSPECIFIED: Role.ValueType  # 0
ROLE_ADMIN: Role.ValueType  # 1
ROLE_MEMBER: Role.ValueType  # 2
ROLE_VIEWER: Role.ValueType  # 3
Global___Role: _TypeAlias = Role  # noqa: Y015

@_typing.final
class User(_message.Message):
    """common messages"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    PLAN_TIER_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    email: _builtins.str
    plan_tier: Global___PlanTier.ValueType
    role: Global___Role.ValueType
    created_at: _builtins.float
    updated_at: _builtins.float
    is_active: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        email: _builtins.str = ...,
        plan_tier: Global___PlanTier.ValueType = ...,
        role: Global___Role.ValueType = ...,
        created_at: _builtins.float = ...,
        updated_at: _builtins.float = ...,
        is_active: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "email", b"email", "id", b"id", "is_active", b"is_active", "plan_tier", b"plan_tier", "role", b"role", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015

@_typing.final
class APIKey(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    RATE_LIMIT_PER_MINUTE_FIELD_NUMBER: _builtins.int
    SCOPES_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    LAST_USED_AT_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    user_id: _builtins.str
    name: _builtins.str
    rate_limit_per_minute: _builtins.int
    created_at: _builtins.float
    last_used_at: _builtins.float
    is_active: _builtins.bool
    @_builtins.property
    def scopes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        name: _builtins.str = ...,
        rate_limit_per_minute: _builtins.int = ...,
        scopes: _abc.Iterable[_builtins.str] | None = ...,
        created_at: _builtins.float = ...,
        last_used_at: _builtins.float | None = ...,
        is_active: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_last_used_at", b"_last_used_at", "last_used_at", b"last_used_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_last_used_at", b"_last_used_at", "created_at", b"created_at", "id", b"id", "is_active", b"is_active", "last_used_at", b"last_used_at", "name", b"name", "rate_limit_per_minute", b"rate_limit_per_minute", "scopes", b"scopes", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__last_used_at: _TypeAlias = _typing.Literal["last_used_at"]  # noqa: Y015
    _WhichOneofArgType__last_used_at: _TypeAlias = _typing.Literal["_last_used_at", b"_last_used_at"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__last_used_at) -> _WhichOneofReturnType__last_used_at | None: ...

Global___APIKey: _TypeAlias = APIKey  # noqa: Y015

@_typing.final
class RegisterUserRequest(_message.Message):
    """user management messages"""

    DESCRIPTOR: _descriptor.Descriptor

    EMAIL_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    PLAN_TIER_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    email: _builtins.str
    password: _builtins.str
    plan_tier: Global___PlanTier.ValueType
    role: Global___Role.ValueType
    def __init__(
        self,
        *,
        email: _builtins.str = ...,
        password: _builtins.str = ...,
        plan_tier: Global___PlanTier.ValueType = ...,
        role: Global___Role.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "password", b"password", "plan_tier", b"plan_tier", "role", b"role"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterUserRequest: _TypeAlias = RegisterUserRequest  # noqa: Y015

@_typing.final
class RegisterUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___User: ...
    def __init__(
        self,
        *,
        user: Global___User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterUserResponse: _TypeAlias = RegisterUserResponse  # noqa: Y015

@_typing.final
class AuthenticateUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EMAIL_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    email: _builtins.str
    password: _builtins.str
    def __init__(
        self,
        *,
        email: _builtins.str = ...,
        password: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "password", b"password"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuthenticateUserRequest: _TypeAlias = AuthenticateUserRequest  # noqa: Y015

@_typing.final
class AuthenticateUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTHENTICATED_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    authenticated: _builtins.bool
    @_builtins.property
    def user(self) -> Global___User: ...
    def __init__(
        self,
        *,
        authenticated: _builtins.bool = ...,
        user: Global___User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authenticated", b"authenticated", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuthenticateUserResponse: _TypeAlias = AuthenticateUserResponse  # noqa: Y015

@_typing.final
class GetUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserRequest: _TypeAlias = GetUserRequest  # noqa: Y015

@_typing.final
class GetUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___User: ...
    def __init__(
        self,
        *,
        user: Global___User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserResponse: _TypeAlias = GetUserResponse  # noqa: Y015

@_typing.final
class GetUserByEmailRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EMAIL_FIELD_NUMBER: _builtins.int
    email: _builtins.str
    def __init__(
        self,
        *,
        email: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserByEmailRequest: _TypeAlias = GetUserByEmailRequest  # noqa: Y015

@_typing.final
class GetUserByEmailResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___User: ...
    def __init__(
        self,
        *,
        user: Global___User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserByEmailResponse: _TypeAlias = GetUserByEmailResponse  # noqa: Y015

@_typing.final
class UpdateUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    PLAN_TIER_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    plan_tier: Global___PlanTier.ValueType
    is_active: _builtins.bool
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        plan_tier: Global___PlanTier.ValueType | None = ...,
        is_active: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_is_active", b"_is_active", "_plan_tier", b"_plan_tier", "is_active", b"is_active", "plan_tier", b"plan_tier"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_is_active", b"_is_active", "_plan_tier", b"_plan_tier", "is_active", b"is_active", "plan_tier", b"plan_tier", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__is_active: _TypeAlias = _typing.Literal["is_active"]  # noqa: Y015
    _WhichOneofArgType__is_active: _TypeAlias = _typing.Literal["_is_active", b"_is_active"]  # noqa: Y015
    _WhichOneofReturnType__plan_tier: _TypeAlias = _typing.Literal["plan_tier"]  # noqa: Y015
    _WhichOneofArgType__plan_tier: _TypeAlias = _typing.Literal["_plan_tier", b"_plan_tier"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_active) -> _WhichOneofReturnType__is_active | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__plan_tier) -> _WhichOneofReturnType__plan_tier | None: ...

Global___UpdateUserRequest: _TypeAlias = UpdateUserRequest  # noqa: Y015

@_typing.final
class UpdateUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___User: ...
    def __init__(
        self,
        *,
        user: Global___User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateUserResponse: _TypeAlias = UpdateUserResponse  # noqa: Y015

@_typing.final
class DeactivateUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeactivateUserRequest: _TypeAlias = DeactivateUserRequest  # noqa: Y015

@_typing.final
class DeactivateUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeactivateUserResponse: _TypeAlias = DeactivateUserResponse  # noqa: Y015

@_typing.final
class AssignRoleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    role: Global___Role.ValueType
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        role: Global___Role.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["role", b"role", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssignRoleRequest: _TypeAlias = AssignRoleRequest  # noqa: Y015

@_typing.final
class AssignRoleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def user(self) -> Global___User: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        user: Global___User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssignRoleResponse: _TypeAlias = AssignRoleResponse  # noqa: Y015

@_typing.final
class CreateAPIKeyRequest(_message.Message):
    """api key management messages"""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SCOPES_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    name: _builtins.str
    @_builtins.property
    def scopes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        name: _builtins.str = ...,
        scopes: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "scopes", b"scopes", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateAPIKeyRequest: _TypeAlias = CreateAPIKeyRequest  # noqa: Y015

@_typing.final
class CreateAPIKeyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_KEY_FIELD_NUMBER: _builtins.int
    PLAIN_KEY_FIELD_NUMBER: _builtins.int
    plain_key: _builtins.str
    """only returned on creation"""
    @_builtins.property
    def api_key(self) -> Global___APIKey: ...
    def __init__(
        self,
        *,
        api_key: Global___APIKey | None = ...,
        plain_key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key", "plain_key", b"plain_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateAPIKeyResponse: _TypeAlias = CreateAPIKeyResponse  # noqa: Y015

@_typing.final
class GetAPIKeyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: _builtins.int
    api_key_id: _builtins.str
    def __init__(
        self,
        *,
        api_key_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key_id", b"api_key_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAPIKeyRequest: _TypeAlias = GetAPIKeyRequest  # noqa: Y015

@_typing.final
class GetAPIKeyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_KEY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def api_key(self) -> Global___APIKey: ...
    def __init__(
        self,
        *,
        api_key: Global___APIKey | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAPIKeyResponse: _TypeAlias = GetAPIKeyResponse  # noqa: Y015

@_typing.final
class ValidateAPIKeyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLAIN_KEY_FIELD_NUMBER: _builtins.int
    plain_key: _builtins.str
    def __init__(
        self,
        *,
        plain_key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["plain_key", b"plain_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateAPIKeyRequest: _TypeAlias = ValidateAPIKeyRequest  # noqa: Y015

@_typing.final
class ValidateAPIKeyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALID_FIELD_NUMBER: _builtins.int
    API_KEY_FIELD_NUMBER: _builtins.int
    valid: _builtins.bool
    @_builtins.property
    def api_key(self) -> Global___APIKey: ...
    def __init__(
        self,
        *,
        valid: _builtins.bool = ...,
        api_key: Global___APIKey | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key", "valid", b"valid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateAPIKeyResponse: _TypeAlias = ValidateAPIKeyResponse  # noqa: Y015

@_typing.final
class ListUserAPIKeysRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListUserAPIKeysRequest: _TypeAlias = ListUserAPIKeysRequest  # noqa: Y015

@_typing.final
class ListUserAPIKeysResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_KEYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def api_keys(self) -> _containers.RepeatedCompositeFieldContainer[Global___APIKey]: ...
    def __init__(
        self,
        *,
        api_keys: _abc.Iterable[Global___APIKey] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_keys", b"api_keys"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListUserAPIKeysResponse: _TypeAlias = ListUserAPIKeysResponse  # noqa: Y015

@_typing.final
class DeactivateAPIKeyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    api_key_id: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        api_key_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key_id", b"api_key_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeactivateAPIKeyRequest: _TypeAlias = DeactivateAPIKeyRequest  # noqa: Y015

@_typing.final
class DeactivateAPIKeyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeactivateAPIKeyResponse: _TypeAlias = DeactivateAPIKeyResponse  # noqa: Y015

@_typing.final
class GetAPIKeyUsageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: _builtins.int
    api_key_id: _builtins.str
    def __init__(
        self,
        *,
        api_key_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key_id", b"api_key_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAPIKeyUsageRequest: _TypeAlias = GetAPIKeyUsageRequest  # noqa: Y015

@_typing.final
class GetAPIKeyUsageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENT_MINUTE_USAGE_FIELD_NUMBER: _builtins.int
    RATE_LIMIT_PER_MINUTE_FIELD_NUMBER: _builtins.int
    current_minute_usage: _builtins.int
    rate_limit_per_minute: _builtins.int
    def __init__(
        self,
        *,
        current_minute_usage: _builtins.int = ...,
        rate_limit_per_minute: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_minute_usage", b"current_minute_usage", "rate_limit_per_minute", b"rate_limit_per_minute"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAPIKeyUsageResponse: _TypeAlias = GetAPIKeyUsageResponse  # noqa: Y015

@_typing.final
class CheckRateLimitRequest(_message.Message):
    """rate limiting messages"""

    DESCRIPTOR: _descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: _builtins.int
    api_key_id: _builtins.str
    def __init__(
        self,
        *,
        api_key_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key_id", b"api_key_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckRateLimitRequest: _TypeAlias = CheckRateLimitRequest  # noqa: Y015

@_typing.final
class CheckRateLimitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ALLOWED_FIELD_NUMBER: _builtins.int
    REMAINING_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    allowed: _builtins.bool
    remaining: _builtins.int
    limit: _builtins.int
    def __init__(
        self,
        *,
        allowed: _builtins.bool = ...,
        remaining: _builtins.int = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowed", b"allowed", "limit", b"limit", "remaining", b"remaining"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckRateLimitResponse: _TypeAlias = CheckRateLimitResponse  # noqa: Y015

@_typing.final
class CheckUserRateLimitRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckUserRateLimitRequest: _TypeAlias = CheckUserRateLimitRequest  # noqa: Y015

@_typing.final
class CheckUserRateLimitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ALLOWED_FIELD_NUMBER: _builtins.int
    REMAINING_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    allowed: _builtins.bool
    remaining: _builtins.int
    limit: _builtins.int
    def __init__(
        self,
        *,
        allowed: _builtins.bool = ...,
        remaining: _builtins.int = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowed", b"allowed", "limit", b"limit", "remaining", b"remaining"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckUserRateLimitResponse: _TypeAlias = CheckUserRateLimitResponse  # noqa: Y015

@_typing.final
class CheckUserPermissionRequest(_message.Message):
    """permission messages"""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    REQUIRED_SCOPE_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    required_scope: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        required_scope: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["required_scope", b"required_scope", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckUserPermissionRequest: _TypeAlias = CheckUserPermissionRequest  # noqa: Y015

@_typing.final
class CheckUserPermissionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HAS_PERMISSION_FIELD_NUMBER: _builtins.int
    has_permission: _builtins.bool
    def __init__(
        self,
        *,
        has_permission: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["has_permission", b"has_permission"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckUserPermissionResponse: _TypeAlias = CheckUserPermissionResponse  # noqa: Y015

@_typing.final
class CheckAPIKeyScopeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: _builtins.int
    REQUIRED_SCOPE_FIELD_NUMBER: _builtins.int
    api_key_id: _builtins.str
    required_scope: _builtins.str
    def __init__(
        self,
        *,
        api_key_id: _builtins.str = ...,
        required_scope: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key_id", b"api_key_id", "required_scope", b"required_scope"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckAPIKeyScopeRequest: _TypeAlias = CheckAPIKeyScopeRequest  # noqa: Y015

@_typing.final
class CheckAPIKeyScopeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HAS_SCOPE_FIELD_NUMBER: _builtins.int
    has_scope: _builtins.bool
    def __init__(
        self,
        *,
        has_scope: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["has_scope", b"has_scope"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckAPIKeyScopeResponse: _TypeAlias = CheckAPIKeyScopeResponse  # noqa: Y015
