# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qbrixproto import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/qbrix.auth.AuthService/RegisterUser',
                request_serializer=auth__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=auth__pb2.RegisterUserResponse.FromString,
                _registered_method=True)
        self.AuthenticateUser = channel.unary_unary(
                '/qbrix.auth.AuthService/AuthenticateUser',
                request_serializer=auth__pb2.AuthenticateUserRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthenticateUserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/qbrix.auth.AuthService/GetUser',
                request_serializer=auth__pb2.GetUserRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.GetUserByEmail = channel.unary_unary(
                '/qbrix.auth.AuthService/GetUserByEmail',
                request_serializer=auth__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserByEmailResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/qbrix.auth.AuthService/UpdateUser',
                request_serializer=auth__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.DeactivateUser = channel.unary_unary(
                '/qbrix.auth.AuthService/DeactivateUser',
                request_serializer=auth__pb2.DeactivateUserRequest.SerializeToString,
                response_deserializer=auth__pb2.DeactivateUserResponse.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/qbrix.auth.AuthService/AssignRole',
                request_serializer=auth__pb2.AssignRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.AssignRoleResponse.FromString,
                _registered_method=True)
        self.CreateAPIKey = channel.unary_unary(
                '/qbrix.auth.AuthService/CreateAPIKey',
                request_serializer=auth__pb2.CreateAPIKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateAPIKeyResponse.FromString,
                _registered_method=True)
        self.GetAPIKey = channel.unary_unary(
                '/qbrix.auth.AuthService/GetAPIKey',
                request_serializer=auth__pb2.GetAPIKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.GetAPIKeyResponse.FromString,
                _registered_method=True)
        self.ValidateAPIKey = channel.unary_unary(
                '/qbrix.auth.AuthService/ValidateAPIKey',
                request_serializer=auth__pb2.ValidateAPIKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.ValidateAPIKeyResponse.FromString,
                _registered_method=True)
        self.ListUserAPIKeys = channel.unary_unary(
                '/qbrix.auth.AuthService/ListUserAPIKeys',
                request_serializer=auth__pb2.ListUserAPIKeysRequest.SerializeToString,
                response_deserializer=auth__pb2.ListUserAPIKeysResponse.FromString,
                _registered_method=True)
        self.DeactivateAPIKey = channel.unary_unary(
                '/qbrix.auth.AuthService/DeactivateAPIKey',
                request_serializer=auth__pb2.DeactivateAPIKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.DeactivateAPIKeyResponse.FromString,
                _registered_method=True)
        self.GetAPIKeyUsage = channel.unary_unary(
                '/qbrix.auth.AuthService/GetAPIKeyUsage',
                request_serializer=auth__pb2.GetAPIKeyUsageRequest.SerializeToString,
                response_deserializer=auth__pb2.GetAPIKeyUsageResponse.FromString,
                _registered_method=True)
        self.CheckRateLimit = channel.unary_unary(
                '/qbrix.auth.AuthService/CheckRateLimit',
                request_serializer=auth__pb2.CheckRateLimitRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckRateLimitResponse.FromString,
                _registered_method=True)
        self.CheckUserRateLimit = channel.unary_unary(
                '/qbrix.auth.AuthService/CheckUserRateLimit',
                request_serializer=auth__pb2.CheckUserRateLimitRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckUserRateLimitResponse.FromString,
                _registered_method=True)
        self.CheckUserPermission = channel.unary_unary(
                '/qbrix.auth.AuthService/CheckUserPermission',
                request_serializer=auth__pb2.CheckUserPermissionRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckUserPermissionResponse.FromString,
                _registered_method=True)
        self.CheckAPIKeyScope = channel.unary_unary(
                '/qbrix.auth.AuthService/CheckAPIKeyScope',
                request_serializer=auth__pb2.CheckAPIKeyScopeRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckAPIKeyScopeResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """user management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAPIKey(self, request, context):
        """api key management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserAPIKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAPIKeyUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckRateLimit(self, request, context):
        """rate limiting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserRateLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserPermission(self, request, context):
        """permissions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAPIKeyScope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=auth__pb2.RegisterUserRequest.FromString,
                    response_serializer=auth__pb2.RegisterUserResponse.SerializeToString,
            ),
            'AuthenticateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateUser,
                    request_deserializer=auth__pb2.AuthenticateUserRequest.FromString,
                    response_serializer=auth__pb2.AuthenticateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=auth__pb2.GetUserRequest.FromString,
                    response_serializer=auth__pb2.GetUserResponse.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=auth__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=auth__pb2.GetUserByEmailResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=auth__pb2.UpdateUserRequest.FromString,
                    response_serializer=auth__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeactivateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateUser,
                    request_deserializer=auth__pb2.DeactivateUserRequest.FromString,
                    response_serializer=auth__pb2.DeactivateUserResponse.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=auth__pb2.AssignRoleRequest.FromString,
                    response_serializer=auth__pb2.AssignRoleResponse.SerializeToString,
            ),
            'CreateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPIKey,
                    request_deserializer=auth__pb2.CreateAPIKeyRequest.FromString,
                    response_serializer=auth__pb2.CreateAPIKeyResponse.SerializeToString,
            ),
            'GetAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAPIKey,
                    request_deserializer=auth__pb2.GetAPIKeyRequest.FromString,
                    response_serializer=auth__pb2.GetAPIKeyResponse.SerializeToString,
            ),
            'ValidateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAPIKey,
                    request_deserializer=auth__pb2.ValidateAPIKeyRequest.FromString,
                    response_serializer=auth__pb2.ValidateAPIKeyResponse.SerializeToString,
            ),
            'ListUserAPIKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserAPIKeys,
                    request_deserializer=auth__pb2.ListUserAPIKeysRequest.FromString,
                    response_serializer=auth__pb2.ListUserAPIKeysResponse.SerializeToString,
            ),
            'DeactivateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateAPIKey,
                    request_deserializer=auth__pb2.DeactivateAPIKeyRequest.FromString,
                    response_serializer=auth__pb2.DeactivateAPIKeyResponse.SerializeToString,
            ),
            'GetAPIKeyUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAPIKeyUsage,
                    request_deserializer=auth__pb2.GetAPIKeyUsageRequest.FromString,
                    response_serializer=auth__pb2.GetAPIKeyUsageResponse.SerializeToString,
            ),
            'CheckRateLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckRateLimit,
                    request_deserializer=auth__pb2.CheckRateLimitRequest.FromString,
                    response_serializer=auth__pb2.CheckRateLimitResponse.SerializeToString,
            ),
            'CheckUserRateLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserRateLimit,
                    request_deserializer=auth__pb2.CheckUserRateLimitRequest.FromString,
                    response_serializer=auth__pb2.CheckUserRateLimitResponse.SerializeToString,
            ),
            'CheckUserPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserPermission,
                    request_deserializer=auth__pb2.CheckUserPermissionRequest.FromString,
                    response_serializer=auth__pb2.CheckUserPermissionResponse.SerializeToString,
            ),
            'CheckAPIKeyScope': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAPIKeyScope,
                    request_deserializer=auth__pb2.CheckAPIKeyScopeRequest.FromString,
                    response_serializer=auth__pb2.CheckAPIKeyScopeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qbrix.auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qbrix.auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/RegisterUser',
            auth__pb2.RegisterUserRequest.SerializeToString,
            auth__pb2.RegisterUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/AuthenticateUser',
            auth__pb2.AuthenticateUserRequest.SerializeToString,
            auth__pb2.AuthenticateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/GetUser',
            auth__pb2.GetUserRequest.SerializeToString,
            auth__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/GetUserByEmail',
            auth__pb2.GetUserByEmailRequest.SerializeToString,
            auth__pb2.GetUserByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/UpdateUser',
            auth__pb2.UpdateUserRequest.SerializeToString,
            auth__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/DeactivateUser',
            auth__pb2.DeactivateUserRequest.SerializeToString,
            auth__pb2.DeactivateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/AssignRole',
            auth__pb2.AssignRoleRequest.SerializeToString,
            auth__pb2.AssignRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/CreateAPIKey',
            auth__pb2.CreateAPIKeyRequest.SerializeToString,
            auth__pb2.CreateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/GetAPIKey',
            auth__pb2.GetAPIKeyRequest.SerializeToString,
            auth__pb2.GetAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/ValidateAPIKey',
            auth__pb2.ValidateAPIKeyRequest.SerializeToString,
            auth__pb2.ValidateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserAPIKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/ListUserAPIKeys',
            auth__pb2.ListUserAPIKeysRequest.SerializeToString,
            auth__pb2.ListUserAPIKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/DeactivateAPIKey',
            auth__pb2.DeactivateAPIKeyRequest.SerializeToString,
            auth__pb2.DeactivateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAPIKeyUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/GetAPIKeyUsage',
            auth__pb2.GetAPIKeyUsageRequest.SerializeToString,
            auth__pb2.GetAPIKeyUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckRateLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/CheckRateLimit',
            auth__pb2.CheckRateLimitRequest.SerializeToString,
            auth__pb2.CheckRateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserRateLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/CheckUserRateLimit',
            auth__pb2.CheckUserRateLimitRequest.SerializeToString,
            auth__pb2.CheckUserRateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/CheckUserPermission',
            auth__pb2.CheckUserPermissionRequest.SerializeToString,
            auth__pb2.CheckUserPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAPIKeyScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.auth.AuthService/CheckAPIKeyScope',
            auth__pb2.CheckAPIKeyScopeRequest.SerializeToString,
            auth__pb2.CheckAPIKeyScopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
