# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qbrixproto import common_pb2 as common__pb2
from qbrixproto import cortex_pb2 as cortex__pb2


class CortexServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FlushBatch = channel.unary_unary(
                '/qbrix.cortex.CortexService/FlushBatch',
                request_serializer=cortex__pb2.FlushBatchRequest.SerializeToString,
                response_deserializer=cortex__pb2.FlushBatchResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/qbrix.cortex.CortexService/GetStats',
                request_serializer=cortex__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=cortex__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/qbrix.cortex.CortexService/Health',
                request_serializer=common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class CortexServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FlushBatch(self, request, context):
        """Force flush pending training batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get training stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FlushBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushBatch,
                    request_deserializer=cortex__pb2.FlushBatchRequest.FromString,
                    response_serializer=cortex__pb2.FlushBatchResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=cortex__pb2.GetStatsRequest.FromString,
                    response_serializer=cortex__pb2.GetStatsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qbrix.cortex.CortexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qbrix.cortex.CortexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CortexService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FlushBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.cortex.CortexService/FlushBatch',
            cortex__pb2.FlushBatchRequest.SerializeToString,
            cortex__pb2.FlushBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.cortex.CortexService/GetStats',
            cortex__pb2.GetStatsRequest.SerializeToString,
            cortex__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.cortex.CortexService/Health',
            common__pb2.HealthCheckRequest.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
