# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cortex.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cortex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qbrixproto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ortex.proto\x12\x0cqbrix.cortex\x1a\x0c\x63ommon.proto\"\xae\x01\n\rFeedbackEvent\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x15\n\rexperiment_id\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x11\n\tarm_index\x18\x04 \x01(\x05\x12\x0e\n\x06reward\x18\x05 \x01(\x01\x12&\n\x07\x63ontext\x18\x06 \x01(\x0b\x32\x15.qbrix.common.Context\x12\x14\n\x0ctimestamp_ms\x18\x07 \x01(\x03\"*\n\x11\x46lushBatchRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\".\n\x12\x46lushBatchResponse\x12\x18\n\x10\x65vents_processed\x18\x01 \x01(\x05\"(\n\x0fGetStatsRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\"w\n\x0f\x45xperimentStats\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_events\x18\x02 \x01(\x03\x12\x16\n\x0epending_events\x18\x03 \x01(\x03\x12\x1f\n\x17last_train_timestamp_ms\x18\x04 \x01(\x03\"@\n\x10GetStatsResponse\x12,\n\x05stats\x18\x01 \x03(\x0b\x32\x1d.qbrix.cortex.ExperimentStats2\xfa\x01\n\rCortexService\x12O\n\nFlushBatch\x12\x1f.qbrix.cortex.FlushBatchRequest\x1a .qbrix.cortex.FlushBatchResponse\x12I\n\x08GetStats\x12\x1d.qbrix.cortex.GetStatsRequest\x1a\x1e.qbrix.cortex.GetStatsResponse\x12M\n\x06Health\x12 .qbrix.common.HealthCheckRequest\x1a!.qbrix.common.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cortex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDBACKEVENT']._serialized_start=45
  _globals['_FEEDBACKEVENT']._serialized_end=219
  _globals['_FLUSHBATCHREQUEST']._serialized_start=221
  _globals['_FLUSHBATCHREQUEST']._serialized_end=263
  _globals['_FLUSHBATCHRESPONSE']._serialized_start=265
  _globals['_FLUSHBATCHRESPONSE']._serialized_end=311
  _globals['_GETSTATSREQUEST']._serialized_start=313
  _globals['_GETSTATSREQUEST']._serialized_end=353
  _globals['_EXPERIMENTSTATS']._serialized_start=355
  _globals['_EXPERIMENTSTATS']._serialized_end=474
  _globals['_GETSTATSRESPONSE']._serialized_start=476
  _globals['_GETSTATSRESPONSE']._serialized_end=540
  _globals['_CORTEXSERVICE']._serialized_start=543
  _globals['_CORTEXSERVICE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
