# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: motor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'motor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qbrixproto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmotor.proto\x12\x0bqbrix.motor\x1a\x0c\x63ommon.proto\"a\n\rSelectRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x15\n\rexperiment_id\x18\x02 \x01(\t\x12&\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x15.qbrix.common.Context\"v\n\x0eSelectResponse\x12\x1e\n\x03\x61rm\x18\x01 \x01(\x0b\x32\x11.qbrix.common.Arm\x12\x1d\n\x15learner_experiment_id\x18\x02 \x01(\t\x12\x15\n\rlearner_index\x18\x03 \x01(\x05\x12\x0e\n\x06policy\x18\x04 \x01(\t2\xa0\x01\n\x0cMotorService\x12\x41\n\x06Select\x12\x1a.qbrix.motor.SelectRequest\x1a\x1b.qbrix.motor.SelectResponse\x12M\n\x06Health\x12 .qbrix.common.HealthCheckRequest\x1a!.qbrix.common.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SELECTREQUEST']._serialized_start=42
  _globals['_SELECTREQUEST']._serialized_end=139
  _globals['_SELECTRESPONSE']._serialized_start=141
  _globals['_SELECTRESPONSE']._serialized_end=259
  _globals['_MOTORSERVICE']._serialized_start=262
  _globals['_MOTORSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
